### ISSUE TITLE
ERR missing util: [tc, sysctl, iptables]

### ISSUE THREAD

**Issue by rshopnil** [bitbrute/evillimiter#42]
https://github.com/bitbrute/evillimiter/issues/36#issue-499084583

Having this same issue. I'm inside a docker container (Ubuntu Xenial)

**Comment by bitbrute** [comment]
Running EvilLimiter from a docker container is not really recommended, since it requires Linux specific kernel tools and changes kernel settings at runtime.

However, if you still want to go that route you should first of all install the required tools:
```apt-get install iptables```
```apt-get install iproute2```

Getting ```sysctl``` to work properly is going to be even more pain in the ass.
Maybe [this thread](https://stackoverflow.com/questions/54845095/cannot-run-sysctl-command-in-dockerfile) will help you out.

**Comment by rshopnil** [comment]
Thanks, @bitbrute. I've worked around this issue successfully. I will try to post an explanation when I get some time. Thanks for your co-operation.

**Comment by kjothisadhanand** [comment]
@rshopnil Hey , can u explain how u resolved this? am getting this error in the windows anaconda environment.

**Comment by leonardus** [comment]
> @rshopnil Hey , can u explain how u resolved this? am getting this error in the windows anaconda environment.

For windows, use [evillimiter for Windows](https://github.com/bitbrute/evillimiter-windows)

**Comment by red-gecko27** [comment]
@rshopnil Hey, did you succeed without using the `--privileged` parameter ? Can you share your dockerfile please ?
