### ISSUE TITLE
No local packages or working download links found for terminaltables

### ISSUE THREAD

**Issue by ferrator07** [bitbrute/evillimiter#9]
Kali-Linux-2019.1-vbox-amd64

When I run the following command: "sudo python3 setup.py install"

I've got this error message:

Installed /usr/local/lib/python3.6/site-packages/evillimiter-1.2.0-py3.6.egg
Processing dependencies for evillimiter==1.2.0
Searching for terminaltables
Reading https://pypi.python.org/simple/terminaltables/
Download error on https://pypi.python.org/simple/terminaltables/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'terminaltables' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for terminaltables
error: Could not find suitable distribution for Requirement.parse('terminaltables')

Any idea why? Thanks in advance!

**Comment by bitbrute** [comment]
Somehow a module required by EvilLimiter could not be downloaded. You can try to do it manually.
```sudo pip3 install terminaltables```

And then try to run the setup again.

**Comment by rz7x** [comment]
I have the same problem and doing it manually doesn't help.
When doing it manually, I get this message:

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting terminaltables
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/                                                                                                             
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/                                                                                                             
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/                                                                                                             
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/                                                                                                             
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/terminaltables/                                                                                                             
  Could not fetch URL https://pypi.org/simple/terminaltables/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/terminaltables/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  ERROR: Could not find a version that satisfies the requirement terminaltables (from versions: none)
ERROR: No matching distribution found for terminaltables
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

Any ideas on how to fix this?
